---
- hosts: all
  remote_user: forescout

  tasks :
       - name: Run tcpdump
         ansible.builtin.command: tcpdump -i replay -w capture.pcap 
         async : 1000
         poll : 0
         register : dum
       - name  :  set facts for the async task 
         set_fact : 
          one_fact : dum
       - debug : 
          var :  ansible_facts.one_fact
   
          
